name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Specify the JDK distribution

      - name: Download JUnit Console Standalone
        run: |
          curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar

      - name: Compile main code
        run: |
          mkdir -p out/production out/test
          javac -d out/production -sourcepath src src/*.java

      - name: Compile test code
        run: |
          javac -d out/test -cp .:junit-platform-console-standalone-1.8.2.jar:out/production -sourcepath test test/*.java

      - name: Run tests
        run: |
          java -jar junit-platform-console-standalone-1.8.2.jar -cp out/production:out/test --scan-class-path
