name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java 12
        run: |
          curl -L -o openjdk-12.tar.gz https://download.java.net/java/early_access/jdk12/33/GPL/openjdk-12-ea+33_linux-x64_bin.tar.gz
          tar -xvzf openjdk-12.tar.gz
          sudo mv jdk-12 /opt/
          sudo update-alternatives --install /usr/bin/java java /opt/jdk-12/bin/java 1
          sudo update-alternatives --set java /opt/jdk-12/bin/java

      - name: Verify Java version
        run: java -version

      - name: Download JUnit Console Standalone
        run: |
          curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar

      - name: List files in current directory
        run: ls -R

      - name: Compile main code
        run: |
          mkdir -p out/production out/test
          javac -d out/production -sourcepath src src/*.java

      - name: Compile test code
        run: |
          javac -d out/test -cp .:junit-platform-console-standalone-1.8.2.jar:out/production -sourcepath test test/*.java

      - name: Run tests
        run: |
          java -jar junit-platform-console-standalone-1.8.2.jar -cp out/production:out/test --scan-class-path
